
if has("syntax")
 syntax on
 endif

set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\



 au BufReadPost *
 \ if line("'\"") > 0 && line("'\"") <= line("$") |
 \ exe "norm g`\"" |
 \ endif

 :colorscheme basic-dark
